collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
typography_spectrum: 0.1684588
color:
  saturation: 0.7473118
  brandStrength: 0
  lightness: 1
  brandColors:
    - '#000000'
    - '#648190'
    - '#213041'
    - '#CFC6B4'
    - '#FFFFF4'
  rhythmicContrast: 0.4856631
layout_spectrum: 0.969534
name: ViewFinder
